# Generated by Django 2.2.7 on 2019-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_remove_notes_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
